// (Q, Σ, δ, q0, F)
export const automatons = [
  {
    name: "Linguagem A",
    states: [
      { label: "q0", value: 0 },
      { label: "q1", value: 1 },
      { label: "q2", value: 2 },
      { label: "q3", value: 3 },
      { label: "q4", value: 4 },
      { label: "q5", value: 5 },
      { label: "q6", value: 6 },
    ],
    alphabet: [
      { label: "a", value: 0 },
      { label: "b", value: 1 },
    ],
    transitions: [
      [1, 2, 3, 6, 6, 6, 6],
      [6, 0, 5, 4, 5, 0, 6],
    ],
    initialState: 0,
    finalStates: [0],
  },
  {
    name: "Linguagem B",
    states: [
      { label: "q0", value: 0 },
      { label: "q1", value: 1 },
    ],
    alphabet: [
      { label: "a", value: 0 },
      { label: "b", value: 1 },
      { label: "c", value: 2 },
      { label: "d", value: 3 },
    ],
    transitions: [
      [1, 1],
      [0, 0],
      [0, 0],
      [0, 0],
    ],
    initialState: 0,
    finalStates: [1],
  },
  {
    name: "Linguagem C",
    states: [
      { label: "q0", value: 0 },
      { label: "q1", value: 1 },
      { label: "q2", value: 2 },
    ],
    alphabet: [
      { label: "0", value: 0 },
      { label: "1", value: 1 },
      { label: "2", value: 2 },
      { label: "3", value: 3 },
      { label: "4", value: 4 },
      { label: "5", value: 5 },
      { label: "6", value: 6 },
      { label: "7", value: 7 },
      { label: "8", value: 8 },
      { label: "9", value: 9 },
    ],
    transitions: [
      [2, 1, 2],
      [1, 1, 2],
      [1, 1, 2],
      [1, 1, 2],
      [1, 1, 2],
      [1, 1, 2],
      [1, 1, 2],
      [1, 1, 2],
      [1, 1, 2],
      [1, 1, 2],
    ],
    initialState: 0,
    finalStates: [1],
  },
  {
    name: "Linguagem D",
    states: [
      { label: "q0", value: 0 },
      { label: "q1", value: 1 },
      { label: "q2", value: 2 },
      { label: "q3", value: 3 },
      { label: "q4", value: 4 },
    ],
    alphabet: [
      { label: "x", value: 0 },
      { label: "y", value: 1 },
    ],
    transitions: [
      [3, 3, 2, 3, 2],
      [4, 1, 4, 1, 4],
    ],
    initialState: 0,
    finalStates: [3, 4],
  },
];